// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace final_efcoretest.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("HourlyPay")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            HourlyPay = 0.0,
                            Name = "Alice",
                            SSN = "123-45-6789",
                            UserId = 1234
                        },
                        new
                        {
                            Id = 1002,
                            HourlyPay = 0.0,
                            Name = "Bob",
                            SSN = "987-65-4321",
                            UserId = 1255
                        },
                        new
                        {
                            Id = 1003,
                            HourlyPay = 0.0,
                            Name = "Charlie",
                            SSN = "456-78-9123",
                            UserId = 1278
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
